### ISSUE TITLE
Cannot run in cron

### ISSUE THREAD

**Issue by airoptix** [quickshiftin/wfpc#1] opened 2016-07-14 21:47 UTC
I can't run it in cronjob. 

In command line works fine, but when adding to cron, does nothing, just sending the usage options by mail. 

In command line is working just this way: php wfpc.php -w d=1 test/warm.xml

Not working like this: ./wfpc.php -w d=1 test/warm.xml (by this way, the same happens: just the usage option)

**Comment by quickshiftin** [comment] 2016-07-14 21:49
The problem is almost certainly that when running the cronjob, your system can't find the correct path to the php executable. To find out the full path to php on your system type
    `which php`
on the command line. Then put that into your cronjob configuration, such as
- \* \* \* \* /usr/bin/php wfpc.php -w -d=1 test/warm.xml

I'm not sure, but if the result of `which php` is different than _/usr/bin/php_ you might be able to update the first line of the script and not have to put the full path in your cronjob configuration.

**Comment by airoptix** [comment] 2016-07-14 21:55
That is the full path. /home/username/public_html/wfpc.php

I am sure, problem is not at my side. In putty, it is working fine.

Cronjob is set properly, another PHP file run perfectly with the same
settings in same directory.
2016. júl. 14. 23:49 ezt írta ("Nathan Nobbe" notifications@github.com):

The problem is almost certainly you need to specify the full path to php in
the cronjob configuration. To find out the full path to php on your system
type

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/quickshiftin/wfpc/issues/1#issuecomment-232802869, or mute
the thread
https://github.com/notifications/unsubscribe/ATcJ5o-_vFlxpSexUf1pW1QcYHy-1UDHks5qVq70gaJpZM4JM4i8
.

**Comment by quickshiftin** [comment] 2016-07-14 21:58
Are the other php files that work marked as executable with a line like `#!/usr/bin/php` at the top? Maybe try taking that line out of the script and using the full path to php as I suggested. There's nothing about the script that should prevent it from working inside a cronjob.

**Comment by airoptix** [comment] 2016-07-14 22:01
Ok. I try this way, and let you know. But the wfpc.php file is found and
run, because it's output is sent to me by the server in mail. But the
output is just the usage instructions immediately, not going through the
sites like in putty. There is not any not found error.
2016. júl. 14. 23:58 ezt írta ("Nathan Nobbe" notifications@github.com):

**Comment by quickshiftin** [comment] 2016-07-14 22:03
Ok. If I have some time I'll see if I can test on my end in a crontab as well.

**Comment by airoptix** [comment] 2016-07-14 22:05
I can try it tomorrow only.
2016. júl. 15. 0:03 ezt írta ("Nathan Nobbe" notifications@github.com):

**Comment by quickshiftin** [comment] 2016-07-14 22:17
Hi, I just tested this in a crontab and it works fine on my machine. I'm not sure exactly what the problem is, here is what I have in my test case for the crontab

`* * * * * /home/nathan/gitRepos/wfpc/wfpc -w -d http://trendy-tees.local/sitemap.xml >> /tmp/wfpc-cron.log`

And on my system `which php` output is _/usr/bin/php_

**Comment by airoptix** [comment] 2016-07-15 11:05
The other php does not have this #!/usr/bin/php at the top. It is the magento's cron.php file. But it also has a cron.sh file, that is related to this cron.php. I'm not too familiar with linux, but I think this .sh file is neccessary to work. 

Anyway, I set up the log file also, but the output is the same: only the usage commands. 

I am sure the wfpc.php file is being run, but not working. Maybe there is some kind of time limit on cron running, and it cannot run through, that's why it immedately goes to usage options. 

I think I give this up.

**Closed as completed** 2016-07-27 03:37 UTC
